#!/bin/sh
#
# Shutdown/logout helper for kiosk.
# Author: T.Jokiel <http://porteus-kiosk.org>

# Kill previous instances:
kill -9 `ps | grep EXIT_MENU | grep -v grep | tr -s ' ' | sed -e 's/^ //g' | cut -d' ' -f1 | tr '\n' ' '` 2>/dev/null

# Offer exit options:
export EXIT_MENU='
<window decorated="true" title="      System" window-position="1" icon-name="kiosk" width-request="200">
<vbox>
<button image-position="2" tooltip-text="Restart X server">
    <input file icon="system-log-out"></input>
    <label>Restart session</label>
    <action>openbox --exit</action>
</button>

<button image-position="2" tooltip-text="Exit menu">
    <input file icon="dialog-cancel"></input>
    <label>Cancel</label>
    <action function="exit">finished</action>
</button>

</vbox>
</window>
'
gtkdialog --program=EXIT_MENU
